export enum TagTypes {
  PLACES = 'Places',
  SUBSCRIPTION = 'Subscription',
  ALL_OPINIONS = 'AllOpinions',
  ALL_VISITS = 'AllVisits',
  OPENING_HOURS = 'OpeningHours',
  VISITS = 'Visits',
  STATUS = 'Status',
  SELECTED_BUSINESS_CHAIN = 'SelectedBusinessChain',
  OPINIONS = 'Opinions',
  SELECTED_PLACE = 'SelectedPlace',
  SELECTED_LOCATIONS = 'SelectedLocations',
  NEWS = 'News',
  AVERAGE_NOTE = 'AverageNote',
  SUBSCRIBERS = 'Subscribers',
  EVENTS = 'Events',
  EVENT = 'Event',
  REWARDS = 'Rewards',
  NOTIFICATIONS = 'Notifications',
  CODES = 'Codes',
  REFERRALS = 'Referrals',
}
